version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: .docker/frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
